title:             wonmin LAB
email:             1mini2@naver.com
description:       원민 테스트 블로그 입니다.
author:            이원민
baseurl:           "/"
url:               "http://1mini2.github.io"
theme:             Minimal

# Social Profiles
twitter_username:  1mini2
github_username:   1mini2
facebook_username: 1mini2

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
